#INCLUDE <TV_PICKIT2_SHIFT_1.C>
SIGNED INT8 CAPSO;
UNSIGNED INT16 DUTY;
VOID PHIM_UP()
{
   IF(!INPUT(UP)&&(DUTY<1000))
   {
      DELAY_MS(20);
      IF(!INPUT(UP))
      {
      DUTY=DUTY+50;
      SET_PWM1_DUTY(DUTY);
      CAPSO++;
      XUAT_4LED_7DOAN_2SO(MA7DOAN[CAPSO/10],MA7DOAN[CAPSO%10]);
      DELAY_MS(200);
      }
   }
}

VOID PHIM_DW()
{
   IF(!INPUT(DW)&&(DUTY>0))
   {
      DELAY_MS(20);
      IF(!INPUT(DW))
      {
      DUTY=DUTY-50;
      CAPSO--;
      XUAT_4LED_7DOAN_2SO(MA7DOAN[CAPSO/10],MA7DOAN[CAPSO%10]);
      SET_PWM1_DUTY(DUTY);
      DELAY_MS(200);
      }
   }
}

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   DC_ENABLE=1;
   OUTPUT_LOW(PIN_C1);
   XUAT_BUZZER_RELAY();
   
   SETUP_CCP1(CCP_PWM);
   SETUP_TIMER_2(T2_DIV_BY_16,249,1);
   DUTY=0;  CAPSO=0;
   XUAT_4LED_7DOAN_2SO(MA7DOAN[CAPSO/10],MA7DOAN[CAPSO%10]);
   SET_PWM1_DUTY(DUTY);
   WHILE(TRUE)
   {
      PHIM_DW();
      PHIM_UP();
      IF(!INPUT(STOP))
      {
         DUTY=0;  CAPSO=0;
         XUAT_4LED_7DOAN_2SO(MA7DOAN[CAPSO/10],MA7DOAN[CAPSO%10]);
         SET_PWM1_DUTY(DUTY);
      }
   }
}
