#INCLUDE <TV_PICKIT2_SHIFT_1.c>
#INCLUDE <TV_PICKIT2_SHIFT_LCD.c>
CONST UNSIGNED CHAR KT1[]={0X00,0X00,0X00,0X00,0XFF,0XFF,0XFF,0XFF};
CONST UNSIGNED CHAR KT2[]={0XFF,0XFF,0XFF,0XFF,0XFF,0XFF,0XFF,0XFF};
SIGNED INT8 I;
VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   SETUP_LCD();
   
   LCD_COMMAND(0X40); //0
   FOR ( I=0;I<8;I++)    { LCD_DATA(KT1[I]); }   
   LCD_COMMAND(0X48); //1
   FOR ( I=0;I<8;I++)    { LCD_DATA(KT2[I]); }   
   
   LCD_GOTO_XY(0,16);
   LCD_DATA(' ');
   LCD_DATA(' ');
   LCD_DATA(0);
   LCD_DATA(1);
   LCD_GOTO_XY(1,16);
   LCD_DATA(0);
   LCD_DATA(1);
   LCD_DATA(1);
   LCD_DATA(1);

   WHILE(TRUE);
}
