#INCLUDE <TV_PICKIT2_SHIFT_1.C>
#INCLUDE <TV_PICKIT2_SHIFT_LCD.C>
VOID MAIN()
{
 SET_UP_PORT_IC_CHOT();
 SETUP_LCD();
 
 LCD_COMMAND(LCD_ADDR_LINE1);
 LCD_DATA("1HIEN THI LCD 20X4** ");
 
  LCD_COMMAND(LCD_ADDR_LINE2);
 LCD_DATA("2DAI HOC SU PHAM KT  ");
 
  LCD_COMMAND(LCD_ADDR_LINE3);
 LCD_DATA("3BO THI NGHIEM VDK  ");
 
  LCD_COMMAND(LCD_ADDR_LINE4);
 LCD_DATA("123456789abcdefghij");
 WHILE(TRUE){}
}
