#INCLUDE  <TV_PICKIT2_SHIFT_1.C>
#INCLUDE  <TV_PICKIT2_SHIFT_GLCD128X64.C>

VOID MAIN ()
{
      SET_UP_PORT_IC_CHOT();
      SETUP_GLCD(GLCD_TEXT_MODE);
      
      GLCD_COMMAND(GLCD_ADDR_LINE1);
      GLCD_DATA("DHSU-PHAM KT HCM");
      
      GLCD_COMMAND(GLCD_ADDR_LINE2);
      GLCD_DATA("BO MON DIEN TU");
      
      GLCD_COMMAND(GLCD_ADDR_LINE3);
      GLCD_DATA("CONG NGHIEP");
      
      GLCD_COMMAND(GLCD_ADDR_LINE4);
      GLCD_DATA("THUC HANH VDK");
      
      WHILE(TRUE) {}
}
