#INCLUDE <TV_PICKIT2_SHIFT_1.c>
#INCLUDE <TV_PICKIT2_SHIFT_LCD.c>
CONST UNSIGNED CHAR TRAITIM[]={0X0A,0X15,0X11,0X11,0X0A,0X04,0,0};
SIGNED INT8 I;
VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   SETUP_LCD();
   LCD_GOTO_XY(0,0);
   LCD_DATA("HIEN THI TRAI TIM");
   
   LCD_COMMAND(0X40); // LUU DU LIEU VAO VUNG NHO CGRAM
   FOR ( I=0;I<8;I++)    { LCD_DATA(TRAITIM[I]); }
   
   LCD_GOTO_XY(1,0); 
   FOR(I=0;I<20;I++)
   {
   DELAY_MS(20);
   LCD_DATA(0);// GOI LENH HIEN THI KI TU SO 0
   }
   WHILE(TRUE);
}
