#INCLUDE <TV_PICKIT2_SHIFT_1.c>
#INCLUDE <TV_PICKIT2_SHIFT_LCD.c>
#INCLUDE <TV_PICKIT2_SHIFT_KEY4X4_138.c>
SIGNED INT8 MP;
VOID HIENTHI_LCD()
{
   LCD_GOTO_XY(0,19);   DELAY_US(20);
   IF(MP<10)   LCD_DATA(MP+0X30);
   ELSE   LCD_DATA(MP+0X37);
}

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   SETUP_LCD();
   LCD_GOTO_XY(0,0);
   LCD_DATA("HAY NHAN PHIM");
   
   WHILE(TRUE)
   {
      DO(MP=KEY_4X4_UP());
      WHILE(MP==0XFF);
      HIENTHI_LCD();
   }
}


