
#INCLUDE <TV_PICKIT2_SHIFT_1.C>
#INCLUDE <TV_PICKIT2_SHIFT_DS1307_I2C.C>

SIGNED INT8 I; 
VOID LCD_HIENTHI_SO_Z_TOADO_XY(SIGNED INT8 LCD_SO,SIGNED INT8 X1, SIGNED Y1)
   {
   LCD_GOTO_XY (X1, Y1) ;
   FOR (I = 0; I < 6; I++)
   {
      IF (I == 3) LCD_GOTO_XY (X1 + 1, Y1);
      LCD_DATA (LCD_SO_X[LCD_SO][I]);
   }
   }
VOID HT_SO_LON()
{
   LCD_GOTO_XY (1, 0);
   LCD_HIENTHI_SO_Z_TOADO_XY (GIO_DS13 / 16 , 2, 0) ;
   LCD_HIENTHI_SO_Z_TOADO_XY (GIO_DS13 % 16 , 2, 3) ;
   LCD_HIENTHI_SO_Z_TOADO_XY (PHUT_DS13 / 16 , 2, 7) ;
   LCD_HIENTHI_SO_Z_TOADO_XY (PHUT_DS13 % 16 , 2, 10) ;
   LCD_HIENTHI_SO_Z_TOADO_XY (GIAY_DS13 / 16 , 2, 14) ;
   LCD_HIENTHI_SO_Z_TOADO_XY (GIAY_DS13 % 16 , 2, 17) ;
}
VOID MAIN()
{
   SET_UP_PORT_IC_CHOT ();
   SETUP_LCD ();
   SET_TRIS_B (0X3C);
   LCD_GOTO_XY (0, 0) ;
   LCD_DATA ("HIEN THI THOI GIAN:");
   DOC_THOI_GIAN_TU_REALTIME ();
   LCD_COMMAND(0X40);
   FOR(I=0;I<64;I++)
   {
   LCD_DATA(LCD_MA_8DOAN[I]);
   }

   IF (MA_DS13 != MA_DS)
   {
      THIET_LAP_THOI_GIAN_HIEN_TAI ();
      NAP_THOI_GIAN_HTAI_VAO_DS13B07 ();
   }
   DOC_THOI_GIAN_TU_REALTIME ();
   GIAYTAM = GIAY_DS13;

   WHILE (TRUE)
   {
      DOC_THOI_GIAN_TU_REALTIME ();

      IF (GIAYTAM != GIAY_DS13)
      {
         GIAYTAM = GIAY_DS13;
         HT_SO_LON();
      }

      DELAY_MS (500);
   }
}

