#INCLUDE <TV_PICKIT2_SHIFT_1.C>
#INCLUDE <TV_PICKIT2_SHIFT_32LED_DON.C>
UNSIGNED INT8 T0,T0_TAM;
VOID MAIN ()
{
   SET_UP_PORT_IC_CHOT();
   SETUP_TIMER_0 (T0_EXT_L_TO_H|T0_DIV_1|T0_8_BIT);
   SET_TIMER0(0);
   T0 = 0;
   XUAT_4LED_7DOAN_GIAIMA_XOA_SO0(T0);            
   WHILE(TRUE)
   {
      T0 = GET_TIMER0();
      XUAT_4LED_7DOAN_GIAIMA_XOA_SO0(T0);
      IF (T0>=101)  SET_TIMER0(1); 
      IF (TTCT_TD==1)      SANG_TAT_32LED(10,0);
      IF (TTCT_TD==2)      SANG_TAT_DAN_PST_32LED(10,0);
      IF (TTCT_TD==3)      SANG_TAT_DAN_TSP_32LED(10,0);
      IF (TTCT_TD==4)      SANG_TAT_DAN_NGOAI_VAO_32LED(10,0);
      IF (TTCT_TD==5)      SANG_TAT_DAN_TRONG_RA_32LED(10,0);      
      IF (TTCT_TD==6)      SANG_DON_PST_32LED(10,0);
      IF (TTCT_TD==7)      DIEM_SANG_DICH_TRAI_MAT_DAN_32LED(10,0);
      IF (TTCT_TD==8)      SANG_DON_TSP_32LED(10,0);
      IF (TTCT_TD==9)      DIEM_SANG_DICH_PHAI_MAT_DAN_32LED(10,0);
      IF (TTCT_TD==10)     SANG_TAT_DAN_TRAI_SANG_PHAI_2X16LED(40,0);
      IF (TTCT_TD==11)     SANG_TAT_DAN_PHAI_SANG_TRAI_2X16LED(40,0);
      IF (TTCT_TD==12)     DIEM_SANG_DI_CHUYEN_PST_32LED(40,0);
      IF (TTCT_TD==13)     DIEM_SANG_DI_CHUYEN_TSP_32LED(40,0);
      IF (TTCT_TD==14)     SANG_DON_TNT_32LED(40,0);
      IF (TTCT_TD==15)     SANG_DON_TTR_32LED(40,0);
      IF (TTCT_TD>15)      TTCT_TD=1;
      XUAT_4LED_7DOAN_2SO(MA7DOAN[TTCT_TD/10],MA7DOAN[TTCT_TD%10]);
   }
}


