#INCLUDE <TV_PICKIT2_SHIFT_1.C>
#INCLUDE <TV_PICKIT2_SHIFT_LCD.C>
UNSIGNED CHAR HANG1[]={"HIEN THI LCD 20X4** "};
UNSIGNED CHAR HANG2[]={"2DAI HOC SU PHAM KT  "};
UNSIGNED CHAR HANG3[]={"3BO THI NGHIEM VDK  "};
UNSIGNED CHAR HANG4[]={"123456789abcdefghij"};
SIGNED INT8 I;
VOID MAIN()
{
 SET_UP_PORT_IC_CHOT();
 SETUP_LCD();
 
  LCD_COMMAND(LCD_ADDR_LINE1);
  FOR(I=0;I<20;I++) {LCD_DATA(HANG1[I]);}
 
  LCD_COMMAND(LCD_ADDR_LINE2);
  FOR(I=0;I<20;I++) {LCD_DATA(HANG2[I]);}
 
  LCD_COMMAND(LCD_ADDR_LINE3);
  FOR(I=0;I<20;I++) {LCD_DATA(HANG3[I]);}
 
  LCD_COMMAND(LCD_ADDR_LINE4);
  FOR(I=0;I<20;I++) {LCD_DATA(HANG4[I]);}
 WHILE(TRUE){}

 
 
}
