
#INCLUDE <TV_PICKIT2_SHIFT_1.c>
#INCLUDE <TV_PICKIT2_SHIFT_GLCD128X64.c>
#INCLUDE<GRAPHICS.C>

UNSIGNED INT8 T0;

VOID GLCD_HIENTHI_T0()
{
   GLCD_COMMAND (0X95) ;
   GLCD_DATA (T0 / 100 % 10 + 0X30);
   GLCD_DATA (T0 / 10 % 10 + 0X30);
   GLCD_DATA (T0 % 10 + 0X30);
}

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT () ;
   SETUP_GLCD (GLCD_TEXT_MODE) ;
   SETUP_GLCD (GLCD_GRAPHIC_MODE) ;
   GLCD_MAU_NEN (0) ;
   glcd_line (0, 0, 50, 50, 1) ;
   glcd_circle (40, 40, 20, 0, 1) ;
   GDRAM_VDK_TO_GDRAM_GLCD_ALL () ;
   
   
   SETUP_TIMER_0 (T0_EXT_L_TO_H|T0_DIV_1|T0_8_BIT);
   SET_TIMER0 (0) ;
   T0 = 0;
   GLCD_COMMAND (GLCD_TEXT_MODE) ;
   GLCD_HIENTHI_T0 () ;
   
   WHILE (TRUE)
   {
      T0 = GET_TIMER0 () ;
      GLCD_HIENTHI_T0 () ;
      XUAT_4LED_7DOAN_4SO (0XFF, MA7DOAN[T0 / 100], MA7DOAN[T0 / 10 % 10], MA7DOAN[T0 % 10]) ;
      IF (T0 >= 101) SET_TIMER0 (0);
   }
}

