
#INCLUDE <TV_PICKIT2_SHIFT_1.C>
#INCLUDE <TV_PICKIT2_SHIFT_DS1307_I2C.C>

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT ();
   SETUP_LCD ();
   LCD_COMMAND (LCD_ADDR_LINE1);
   LCD_DATA ("CLOCK:");
   DOC_THOI_GIAN_TU_REALTIME (); // note
   IF (MA_DS13 != MA_DS)
   {
      THIET_LAP_THOI_GIAN_HIEN_TAI ();
      NAP_THOI_GIAN_HTAI_VAO_DS13B07 ();
   }

   //THIET_LAP_THOI_GIAN_HIEN_TAI ();
   //NAP_THOI_GIAN_HTAI_VAO_DS13B07 ();
   DOC_THOI_GIAN_TU_REALTIME ();
   GIAYTAM = GIAY_DS13;

   WHILE (TRUE)
   {
      DOC_THOI_GIAN_TU_REALTIME ();
      HIEN_THI_THOI_GIAN_DS13B07 ();      // da xoa thu ko can thiet
   }
}

