#INCLUDE <TV_PICKIT2_SHIFT_1.c>
UNSIGNED INT16 T0;
UNSIGNED INT16 DONVI, CHUC, TRAM,NGHIN;
VOID GIAI_MA_HIEN_THI (UNSIGNED INT16 TAM)
{
   DONVI=MA7DOAN[TAM%10];
   CHUC=MA7DOAN[TAM%100/10];
   TRAM=MA7DOAN[TAM%1000/100];
   NGHIN=MA7DOAN[TAM/1000];
   IF (NGHIN==0XC0)
   {
      NGHIN=0XFF;
      IF (TRAM==0XC0) 
      {
         TRAM=0XFF;
         IF(CHUC==0XC0)
         {
            CHUC=0XFF;
         }
      }    
   }
   XUAT_4LED_7DOAN_4SO(NGHIN,TRAM,CHUC,DONVI);
}
VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   SETUP_TIMER_0 (T0_EXT_L_TO_H|T0_DIV_1);
   SET_TIMER0(9970); // SET_TRIMER0(0);
   WHILE(TRUE)
   {
      T0=GET_TIMER0();
      GIAI_MA_HIEN_THI (T0);
      IF (T0>=10000) SET_TIMER0(0);
   }
}
