
#INCLUDE <TV_PICKIT2_SHIFT_1.C>

UNSIGNED INT8 LED7DQ[8]={0XC0,0XF9,0XA4,0XB0,0X99,0X92,0X82,0XF8};

UNSIGNED INT8 I;

VOID HIEN_THI_8LED()
{
   FOR (I = 0; I < 8; I++)
   {
      XUAT_8LED_7DOAN_QUET_2 (I, LED7DQ[I]);
      DELAY_US (100);
      XUAT_8LED_7DOAN_QUET_TAT_LED ();
   }
}

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT ();

   WHILE (TRUE)
   {
      HIEN_THI_8LED ();
   }
}

