#INCLUDE <TV_PICKIT2_SHIFT_1.C>
#INCLUDE <TV_PICKIT2_SHIFT_STEP_MOTOR.C>

VOID MAIN()
{
   SET_UP_PORT_IC_CHOT();
   STEPMOTOR_DELAY=20;
   STEPMOTOR_ONOFF=1; //DE KHOI CANH BAO
   WHILE(TRUE)
   {
   WHILE(INPUT(ON));
   DO
   {
      STEP_MOTOR_QUAY_NGHICH_FS();
      DELAY_MS(STEPMOTOR_DELAY);
   }
   WHILE(INPUT(OFF));
   }
}
