UNSIGNED  INT8 STEPMOTOR_FULLSTEP[]=  {0X1D,0X17,0X1B,0X0F};
UNSIGNED  INT8 STEPMOTOR_HALFSTEP[]=  {0X1D,0X15,0X17,0X13,0X03,0X0B,0X09,0X0D};
UNSIGNED  INT8 STEPMOTOR_I=0, STEPMOTOR_DELAY;
INT1 STEPMOTOR_TN=0,STEPMOTOR_ONOFF=0;
//UNSIGNED INT8 SO_BUOC;
VOID STEP_MOTOR_QUAY_THUAN_FS()
{
      RBDC=RBDC & 0xFFE0;           
      RBDC=RBDC | STEPMOTOR_FULLSTEP[STEPMOTOR_I];
      XUAT_BUZZER_RELAY(); 
      STEPMOTOR_I++;
      //SO_BUOC++;
      STEPMOTOR_I = STEPMOTOR_I & 0X03;
}
VOID STEP_MOTOR_QUAY_NGHICH_FS()
{
      RBDC=RBDC & 0xFFE0;           
      RBDC=RBDC | STEPMOTOR_FULLSTEP[STEPMOTOR_I];
      XUAT_BUZZER_RELAY(); 
      STEPMOTOR_I--;
      //SO_BUOC++;
      STEPMOTOR_I = STEPMOTOR_I & 0X03;
}
VOID MOTOR_STEP_RUN_FS()
{
   IF (STEPMOTOR_TN) STEP_MOTOR_QUAY_THUAN_FS();
   ELSE           STEP_MOTOR_QUAY_NGHICH_FS();
}

VOID STEP_MOTOR_QUAY_THUAN_HS()
{
      RBDC=RBDC & 0xE0;           
      RBDC=RBDC | STEPMOTOR_HALFSTEP[STEPMOTOR_I];
      XUAT_BUZZER_RELAY(); 
      STEPMOTOR_I++;
      STEPMOTOR_I = STEPMOTOR_I & 0X07;
}
VOID STEP_MOTOR_QUAY_NGHICH_HS()
{
      RBDC=RBDC & 0xE0;           
      RBDC=RBDC | STEPMOTOR_HALFSTEP[STEPMOTOR_I];
      XUAT_BUZZER_RELAY(); 
      STEPMOTOR_I--;
      STEPMOTOR_I = STEPMOTOR_I & 0X07;
}
VOID MOTOR_STEP_RUN_HS()
{
   IF (STEPMOTOR_TN) STEP_MOTOR_QUAY_THUAN_HS();
   ELSE           STEP_MOTOR_QUAY_NGHICH_HS();
}

