#INCLUDE <TV_PICKIT2_SHIFT_FONT.c>
CONST UNSIGNED INT8 MA_QUET_HANG[8]={0x01,0x02,0x04,0x08,0x80,0x40,0x20,0x10};
#DEFINE  SLKT_HIENTHI    40
UNSIGNED INT8   DL_HIENTHI[6*SLKT_HIENTHI];
UNSIGNED INT8   SLKT;

UNSIGNED INT8  DL_COT_CD[48]={};
UNSIGNED INT8  DL_COT_DICH[48]={};
UNSIGNED INT8  DL_COT_CD_DO[24]={};
UNSIGNED INT8  DL_COT_CD_XANH[24]={};
UNSIGNED INT8  DL_COT_DICH_D[24]={};
UNSIGNED INT8  DL_COT_DICH_X[24]={};
UNSIGNED INT16 VTKT1;

UNSIGNED INT8 DOI_1_BIT_1_SANG_THUTU(UNSIGNED INT8 BX)
{   
   UNSIGNED INT8 TTCOT=0;
   BX= BX>>1;
   WHILE(BX!=0)
   {
      TTCOT++;
      BX= BX>>1;
   }   
   RETURN(TTCOT);
}

VOID LAY_SO_LUONG_KY_TU_CHUOI()
{   
   SLKT=0;
   WHILE(CHUOI_HIENTHI[SLKT])
   {
      SLKT++;}
      XUAT_4LED_7DOAN_GIAIMA_XOA_SO0(SLKT);
}

VOID XOA_DL_HIENTHI()
{   
   UNSIGNED INT8  J;     
   FOR(J=0;J<6*SLKT_HIENTHI ;J++)  
   DL_HIENTHI[J]=0;
}

VOID LAY_MA_1_SO_MATRAN(UNSIGNED INT8 SO, UNSIGNED INT8 VITRI_LUU)
{   
   UNSIGNED INT8  N,J;
   N=0;   
   SO = SO + 26;      
   FOR(J=0;J<6 ;J++,N++)  
   DL_HIENTHI[N+VITRI_LUU*6]=MATRAN_KYTU[SO][J];
}

VOID LAY_MA_KY_TU(UNSIGNED INT8 SLKT_X)
{   
   UNSIGNED INT8  KYTU,I,N,J;
   N=0;
   FOR (I=0; I<SLKT_X; I++)
   {
      KYTU = CHUOI_HIENTHI[I];
      IF ((KYTU>=0X41)&&(KYTU<=0X5A))        KYTU = KYTU - 0X41;
      ELSE IF ((KYTU>=0X30)&&(KYTU<=0X39))   KYTU = (KYTU - 0X30) + 26;      
      FOR(J=0;J<6 ;J++,N++)  
      DL_HIENTHI[N]=MATRAN_KYTU[KYTU][J];
   }
}


VOID TINH_VI_TRI_KY_TU(UNSIGNED INT16 K)
{  
   UNSIGNED INT8 Y;
   Y=K/6;      
   VTKT1=(Y*6)+5; 
}
//SAP XEP CAC KY TU MAU XANH 1,2,3,4
VOID KY_TU_XANH_SO_1(UNSIGNED INT8 K)
{
      DL_COT_CD[1]=DL_HIENTHI[K+3];    DL_COT_CD[3]=DL_HIENTHI[K+2];
      DL_COT_CD[5]=DL_HIENTHI[K+1];    DL_COT_CD[7]=DL_HIENTHI[K+0];      
      DL_COT_CD[8]=DL_HIENTHI[K+4];    DL_COT_CD[10]=DL_HIENTHI[K+5];
}
VOID KY_TU_XANH_SO_2(UNSIGNED INT8 K)
{
      DL_COT_CD[12]=DL_HIENTHI[K+6];   DL_COT_CD[14]=DL_HIENTHI[K+7];      
      DL_COT_CD[17]=DL_HIENTHI[K+11];  DL_COT_CD[19]=DL_HIENTHI[K+10];
      DL_COT_CD[21]=DL_HIENTHI[K+9];   DL_COT_CD[23]=DL_HIENTHI[K+8];       
}
VOID KY_TU_XANH_SO_3(UNSIGNED INT8 K)
{
      DL_COT_CD[24]=DL_HIENTHI[K+12];  DL_COT_CD[26]=DL_HIENTHI[K+13];
      DL_COT_CD[28]=DL_HIENTHI[K+14];  DL_COT_CD[30]=DL_HIENTHI[K+15];      
      DL_COT_CD[37]=DL_HIENTHI[K+17];  DL_COT_CD[39]=DL_HIENTHI[K+16]; 
}
VOID KY_TU_XANH_SO_4(UNSIGNED INT8 K)
{    
      DL_COT_CD[33]=DL_HIENTHI[K+19];  DL_COT_CD[35]=DL_HIENTHI[K+18];
      DL_COT_CD[40]=DL_HIENTHI[K+20];  DL_COT_CD[42]=DL_HIENTHI[K+21];
      DL_COT_CD[44]=DL_HIENTHI[K+22];  DL_COT_CD[46]=DL_HIENTHI[K+23];       
}

//SAP XEP CAC KY TU MAU DO 1,2,3,4
VOID KY_TU_DO_SO_1(UNSIGNED INT8 K)
{
      DL_COT_CD[0]=DL_HIENTHI[K+3];   DL_COT_CD[2]=DL_HIENTHI[K+2];
      DL_COT_CD[4]=DL_HIENTHI[K+1];   DL_COT_CD[6]=DL_HIENTHI[K+0];      
      DL_COT_CD[9]=DL_HIENTHI[K+4];   DL_COT_CD[11]=DL_HIENTHI[K+5];
}
VOID KY_TU_DO_SO_2(UNSIGNED INT8 K)
{
      DL_COT_CD[13]=DL_HIENTHI[K+6];  DL_COT_CD[15]=DL_HIENTHI[K+7];      
      DL_COT_CD[16]=DL_HIENTHI[K+11]; DL_COT_CD[18]=DL_HIENTHI[K+10];
      DL_COT_CD[20]=DL_HIENTHI[K+9];  DL_COT_CD[22]=DL_HIENTHI[K+8];
}
VOID KY_TU_DO_SO_3(UNSIGNED INT8 K)
{      
      DL_COT_CD[25]=DL_HIENTHI[K+12]; DL_COT_CD[27]=DL_HIENTHI[K+13];
      DL_COT_CD[29]=DL_HIENTHI[K+14]; DL_COT_CD[31]=DL_HIENTHI[K+15];      
      DL_COT_CD[36]=DL_HIENTHI[K+17]; DL_COT_CD[38]=DL_HIENTHI[K+16]; 
}
VOID KY_TU_DO_SO_4(UNSIGNED INT8 K)
{
      DL_COT_CD[32]=DL_HIENTHI[K+19]; DL_COT_CD[34]=DL_HIENTHI[K+18]; 
      DL_COT_CD[41]=DL_HIENTHI[K+20]; DL_COT_CD[43]=DL_HIENTHI[K+21];
      DL_COT_CD[45]=DL_HIENTHI[K+22]; DL_COT_CD[47]=DL_HIENTHI[K+23]; 
}
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
VOID KY_TU_XANH_HOAC_DO_SO_1(UNSIGNED INT8 K)
{     
      TINH_VI_TRI_KY_TU(K);      
      IF (DL_HIENTHI[VTKT1]==0)
      {
         DL_COT_CD[1]=DL_HIENTHI[K+3];    DL_COT_CD[3]=DL_HIENTHI[K+2];
         DL_COT_CD[5]=DL_HIENTHI[K+1];    DL_COT_CD[7]=DL_HIENTHI[K+0];      
         DL_COT_CD[8]=DL_HIENTHI[K+4];    DL_COT_CD[10]=DL_HIENTHI[K+5];
      }
      ELSE
      {
         DL_COT_CD[0]=DL_HIENTHI[K+3];   DL_COT_CD[2]=DL_HIENTHI[K+2];
         DL_COT_CD[4]=DL_HIENTHI[K+1];   DL_COT_CD[6]=DL_HIENTHI[K+0];      
         DL_COT_CD[9]=DL_HIENTHI[K+4];   DL_COT_CD[11]=DL_HIENTHI[K+5];     
     }
}
VOID KY_TU_XANH_HOAC_DO_SO_2(UNSIGNED INT8 K)
{
      IF (DL_HIENTHI[VTKT1+6]==0)
      {
         DL_COT_CD[12]=DL_HIENTHI[K+6];   DL_COT_CD[14]=DL_HIENTHI[K+7];      
         DL_COT_CD[17]=DL_HIENTHI[K+11];  DL_COT_CD[19]=DL_HIENTHI[K+10];
         DL_COT_CD[21]=DL_HIENTHI[K+9];   DL_COT_CD[23]=DL_HIENTHI[K+8];     
      }
      ELSE
      {
         DL_COT_CD[13]=DL_HIENTHI[K+6];  DL_COT_CD[15]=DL_HIENTHI[K+7];      
         DL_COT_CD[16]=DL_HIENTHI[K+11]; DL_COT_CD[18]=DL_HIENTHI[K+10];
         DL_COT_CD[20]=DL_HIENTHI[K+9];  DL_COT_CD[22]=DL_HIENTHI[K+8];
     }
}
VOID KY_TU_XANH_HOAC_DO_SO_3(UNSIGNED INT8 K)
{
      IF (DL_HIENTHI[VTKT1+12]==0)
      {
         DL_COT_CD[24]=DL_HIENTHI[K+12];  DL_COT_CD[26]=DL_HIENTHI[K+13];
         DL_COT_CD[28]=DL_HIENTHI[K+14];  DL_COT_CD[30]=DL_HIENTHI[K+15];      
         DL_COT_CD[37]=DL_HIENTHI[K+17];  DL_COT_CD[39]=DL_HIENTHI[K+16]; 
      }
      ELSE
      {
         DL_COT_CD[25]=DL_HIENTHI[K+12]; DL_COT_CD[27]=DL_HIENTHI[K+13];
         DL_COT_CD[29]=DL_HIENTHI[K+14]; DL_COT_CD[31]=DL_HIENTHI[K+15];      
         DL_COT_CD[36]=DL_HIENTHI[K+17]; DL_COT_CD[38]=DL_HIENTHI[K+16]; 
     }
}
VOID KY_TU_XANH_HOAC_DO_SO_4(UNSIGNED INT8 K)
{
      IF (DL_HIENTHI[VTKT1+18]==0)
      {
         DL_COT_CD[33]=DL_HIENTHI[K+19];  DL_COT_CD[35]=DL_HIENTHI[K+18];
         DL_COT_CD[40]=DL_HIENTHI[K+20];  DL_COT_CD[42]=DL_HIENTHI[K+21];
         DL_COT_CD[44]=DL_HIENTHI[K+22];  DL_COT_CD[46]=DL_HIENTHI[K+23];       
      }
      ELSE  
      {
         DL_COT_CD[32]=DL_HIENTHI[K+19]; DL_COT_CD[34]=DL_HIENTHI[K+18]; 
         DL_COT_CD[41]=DL_HIENTHI[K+20]; DL_COT_CD[43]=DL_HIENTHI[K+21];
         DL_COT_CD[45]=DL_HIENTHI[K+22]; DL_COT_CD[47]=DL_HIENTHI[K+23]; 
     }
}

VOID SAPXEP_VITRI_48BYTE_MAU_THEO_KYTU(UNSIGNED INT8 K1)
{
      KY_TU_XANH_HOAC_DO_SO_1(K1);
      KY_TU_XANH_HOAC_DO_SO_2(K1);   
      KY_TU_XANH_HOAC_DO_SO_3(K1);
      KY_TU_XANH_HOAC_DO_SO_4(K1);         
}
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
VOID SAPXEP_VITRI_48BYTE_COT_XANH(UNSIGNED INT8 K1)
{
      KY_TU_XANH_SO_1(K1);   KY_TU_XANH_SO_2(K1);
      KY_TU_XANH_SO_3(K1);   KY_TU_XANH_SO_4(K1);                   
}
VOID SAPXEP_VITRI_48BYTE_COT_DO(UNSIGNED INT8 K1)
{   
      KY_TU_DO_SO_1(K1);  KY_TU_DO_SO_2(K1);
      KY_TU_DO_SO_3(K1);  KY_TU_DO_SO_4(K1);     
}

VOID SAPXEP_VITRI_XANH_DO_XANH_DO(UNSIGNED INT8 K1)
{
      KY_TU_XANH_SO_1(K1);  KY_TU_DO_SO_2(K1);
      KY_TU_XANH_SO_3(K1);  KY_TU_DO_SO_4(K1);
}
VOID SAPXEP_VITRI_DO_XANH_DO_XANH(UNSIGNED INT8 K1)
{
      KY_TU_DO_SO_1(K1);  KY_TU_XANH_SO_2(K1);
      KY_TU_DO_SO_3(K1);  KY_TU_XANH_SO_4(K1);
}

VOID SAPXEP_VITRI_XANH_XANH_DO_DO(UNSIGNED INT8 K1)
{
      KY_TU_XANH_SO_1(K1);  KY_TU_XANH_SO_2(K1);
      KY_TU_DO_SO_3(K1);     KY_TU_DO_SO_4(K1);
}
VOID SAPXEP_VITRI_DO_DO_XANH_XANH(UNSIGNED INT8 K1)
{
      KY_TU_DO_SO_1(K1);  KY_TU_DO_SO_2(K1);
      KY_TU_XANH_SO_3(K1);  KY_TU_XANH_SO_4(K1);
}

VOID XOA_DL_48_COT()
{
   UNSIGNED INT8 J1;
      FOR (J1=0;J1<48;J1++) DL_COT_CD[J1]=0;
}
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
VOID  COPY_48_COT_HIENTHI()
{     UNSIGNED INT8 I;
      FOR (I=0;I<48;I++)   DL_COT_DICH[I]=DL_COT_CD[I];
}

VOID XUAT_1BIT_CUA_48_COT_HIENTHI()
{     UNSIGNED INT8 I;
      FOR (I=0;I<48;I++)   DL_COT_DICH[I]=XUAT_1BIT(DL_COT_DICH[I]);
}
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
VOID  COPY_24_COT_HIENTHI_XANH(UNSIGNED INT8 K1)
{     UNSIGNED INT8 I;
      FOR (I=0;I<24;I++)   
      DL_COT_CD_XANH[I+K1]=DL_HIENTHI[I+K1];
}
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
VOID  COPY_24_COT_HIENTHI_DO(UNSIGNED INT8 K1)
{     UNSIGNED INT8 I;
      FOR (I=0;I<24;I++)   
      DL_COT_CD_DO[I+K1]=DL_HIENTHI[I+K1];
}
//XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
VOID  COPY_24_COT_HIENTHI_XANH_DO_DE_DICH()
{     UNSIGNED INT8 I;
      FOR (I=0;I<48;I++)   
      {
         DL_COT_DICH_D[I]=DL_COT_CD_DO[I];
         DL_COT_DICH_X[I]=DL_COT_CD_XANH[I];     
      }
} 
VOID XOA_DL_24_COT_XANH_DO()
{
   UNSIGNED INT8 J1;
      FOR (J1=0;J1<24;J1++) 
      {  
         DL_COT_CD_DO[J1]=0;DL_COT_CD_XANH[J1]=0;
      }
}
VOID XUAT_DULIEU_HIENTHI_MATRAN()
{    
      MO_LED_MATRAN;
      MO_IC_74573_B_THONG_DL();
      OUTPUT_HIGH(RCK_MATRANLED); OUTPUT_LOW(RCK_MATRANLED); 
      CHOT_IC_74573_B_GOI_DU_LIEU;  
}

VOID XUAT_1BIT_CUA_48_COT_HIENTHI_C2()
{     
   SIGNED IX;
   FOR(IX=3;IX>-1;IX--)
   {
      DL_COT_DICH_D[IX]=XUAT_1BIT(DL_COT_DICH_D[IX]);
      DL_COT_DICH_X[IX]=XUAT_1BIT(DL_COT_DICH_X[IX]);
   }
   FOR(IX=4;IX<8;IX++)
   {
      DL_COT_DICH_D[IX]=XUAT_1BIT(DL_COT_DICH_D[IX]);
      DL_COT_DICH_X[IX]=XUAT_1BIT(DL_COT_DICH_X[IX]);
      }
   FOR(IX=11;IX>7;IX--)
   {
      DL_COT_DICH_D[IX]=XUAT_1BIT(DL_COT_DICH_D[IX]);
      DL_COT_DICH_X[IX]=XUAT_1BIT(DL_COT_DICH_X[IX]);
   }
       FOR(IX=12;IX<16;IX++)
   {
      DL_COT_DICH_D[IX]=XUAT_1BIT(DL_COT_DICH_D[IX]);
      DL_COT_DICH_X[IX]=XUAT_1BIT(DL_COT_DICH_X[IX]);
      }
      
      FOR(IX=19;IX>15;IX--)
   {
      DL_COT_DICH_D[IX]=XUAT_1BIT(DL_COT_DICH_D[IX]);
      DL_COT_DICH_X[IX]=XUAT_1BIT(DL_COT_DICH_X[IX]);
   }
       FOR(IX=20;IX<24;IX++)
   {
      DL_COT_DICH_D[IX]=XUAT_1BIT(DL_COT_DICH_D[IX]);
      DL_COT_DICH_X[IX]=XUAT_1BIT(DL_COT_DICH_X[IX]);
      }      
}

VOID HIEN_THI_MA_TRAN_QUET_HANG(UNSIGNED INT8 CK)
{
   UNSIGNED INT8 J,I;
   FOR (I=0;I<CK;I++)
   {
      COPY_48_COT_HIENTHI();
      FOR(J=0;J<8;J++)
         {
               XUAT_1BIT_CUA_48_COT_HIENTHI();
               XUAT_2BYTE(MA_QUET_HANG[J]);                  
               XUAT_DULIEU_HIENTHI_MATRAN();                                                                      
               DELAY_US(500); 
               XUAT_MATRANLED(0,0,0,0);
         }
   }
}

 
